import os
import subprocess
import glob
import shutil
import traceback


Import('env')
Import('libmoosecat')

def clar_walk_dir(root_path='lib', output='.out'):
    '''
    '''
    print('- clar: Walking & Copying files.')
    out_dir = os.path.join(root_path, output)
    try:
        shutil.rmtree(out_dir)
    except:
        pass

    os.mkdir(out_dir)

    for root, dirs, files in os.walk(root_path):
        for leaf in files:
            if leaf.endswith('.c'):
                shutil.copy(os.path.join(root, leaf), out_dir)

    print('- clar: Running clar mixer.')
    subprocess.call(['python', 'clar/clar.py', out_dir])
    return glob.glob(os.path.join(out_dir, '*.c'))

try:
    env.Program(
            target='test',
            LIBS=[libmoosecat],
            source=clar_walk_dir())
except:
    print('- not building clar tests: ' + traceback.format_exc())
