from .sidebar import Sidebar
from .timeslide import Timeslide
from .volume import Volume
from .play_buttons import PlayButtons
from .title_label import TitleLabel
from .mode_buttons import ModeButtons
from .statistic_label import StatisticLabel
from .infobar import InfoBar
from .next_song_label import NextSongLabel
from .status_spinner import StatusSpinner
from .menu import Menu
